import { useEffect, useRef, useState } from "react";
import { createFileRoute, redirect } from "@tanstack/react-router";
import { authStore } from "@/lib/auth-store";
import { RefreshCw, Archive, Download, Loader2 } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { apiClient } from "@/lib/api/api-client";
import { http } from "@/lib/api/axios";
import { ENDPOINTS } from "@/lib/api/endpoints";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { SurfaceCard } from "@/components/shared/Card";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/portal/reports")({
  head: () => ({ meta: [{ title: "Reports · 360CRD" }] }),
  beforeLoad: () => {
    if (typeof window === "undefined") return;
    const perms = authStore.getState().user?.permissions ?? [];
    if (!perms.includes("report:read") && !perms.includes("*") && !perms.includes("*:*")) {
      throw redirect({ to: "/portal/dashboard" });
    }
  },
  component: ReportsPage,
});

const STATUS_COLOR: Record<string, string> = {
  PENDING:    "bg-yellow-500/10 text-yellow-600 border-yellow-500/20",
  PROCESSING: "bg-blue-500/10 text-blue-600 border-blue-500/20",
  COMPLETED:  "bg-green-500/10 text-green-600 border-green-500/20",
  FAILED:     "bg-red-500/10 text-red-600 border-red-500/20",
};

function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  async function load() {
    setLoading(true);
    try {
      const res = await apiClient.get<any>(ENDPOINTS.reports.list, { limit: 20 });
      setReports(res.data ?? []);
    } catch {
      toast.error("Failed to load reports");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, []);

  // Poll while any report is processing
  useEffect(() => {
    const hasPending = reports.some((r) => r.status === "PENDING" || r.status === "PROCESSING");
    if (hasPending) {
      if (!pollRef.current) {
        pollRef.current = setInterval(async () => {
          try {
            const res = await apiClient.get<any>(ENDPOINTS.reports.list, { limit: 20 });
            setReports(res.data ?? []);
          } catch { /* ignore */ }
        }, 4000);
      }
    } else {
      if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
    }
    return () => { if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; } };
  }, [reports]);

  async function handleDownload(report: any) {
    setDownloading(report.id);
    try {
      const res = await http.get<Blob>(ENDPOINTS.reports.download(report.id), { responseType: "blob" });
      const url = URL.createObjectURL(res.data as Blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${report.title.replace(/[^a-z0-9]/gi, "_")}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      toast.error("Failed to download report");
    } finally {
      setDownloading(null);
    }
  }

  return (
    <AppShell>
      <div className="mx-auto max-w-[1400px] space-y-6 animate-in fade-in duration-300">
        <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight md:text-3xl">Reports</h1>
            <p className="mt-1 text-sm text-muted-foreground">View and download your compliance reports.</p>
          </div>
          <Button variant="outline" size="sm" onClick={load} disabled={loading}>
            <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />
          </Button>
        </div>

        {/* Reports list — no generate section for portal users */}
        {loading ? (
          <div className="space-y-3">
            {Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-16 rounded-lg" />)}
          </div>
        ) : reports.length === 0 ? (
          <SurfaceCard className="flex flex-col items-center justify-center py-12">
            <Archive className="h-10 w-10 text-muted-foreground/40" />
            <p className="mt-4 text-sm font-medium">No reports available</p>
            <p className="mt-1 text-xs text-muted-foreground">Reports generated by your administrator will appear here.</p>
          </SurfaceCard>
        ) : (
          <div className="space-y-2">
            {reports.map((r: any) => (
              <div key={r.id} className="flex items-center gap-4 rounded-lg border border-border/60 bg-card/50 px-4 py-3">
                <Archive className="h-5 w-5 shrink-0 text-muted-foreground" />
                <div className="min-w-0 flex-1">
                  <p className="font-medium text-foreground">{r.title}</p>
                  <p className="text-xs text-muted-foreground">
                    {r.type?.replace(/_/g, " ")} · {new Date(r.createdAt).toLocaleDateString()}
                    {r.generatedAt && ` · Generated ${new Date(r.generatedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`}
                  </p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className={cn("rounded-full border px-2 py-0.5 text-[10px] font-medium", STATUS_COLOR[r.status] ?? "bg-gray-500/10 text-gray-600")}>
                    {r.status === "PROCESSING"
                      ? <span className="flex items-center gap-1"><Loader2 className="h-2.5 w-2.5 animate-spin" />{r.status}</span>
                      : r.status}
                  </span>
                  {r.status === "COMPLETED" && (
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-7 gap-1 text-xs"
                      disabled={downloading === r.id}
                      onClick={() => handleDownload(r)}
                    >
                      {downloading === r.id
                        ? <Loader2 className="h-3 w-3 animate-spin" />
                        : <Download className="h-3 w-3" />
                      }
                      Download
                    </Button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </AppShell>
  );
}
