/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppWasteRouteImport } from './routes/_authenticated/app/waste'
import { Route as AuthenticatedAppTrainingRouteImport } from './routes/_authenticated/app/training'
import { Route as AuthenticatedAppSitesRouteImport } from './routes/_authenticated/app/sites'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app/reports'
import { Route as AuthenticatedAppPpeRouteImport } from './routes/_authenticated/app/ppe'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app/notifications'
import { Route as AuthenticatedAppInductionsRouteImport } from './routes/_authenticated/app/inductions'
import { Route as AuthenticatedAppIncidentsRouteImport } from './routes/_authenticated/app/incidents'
import { Route as AuthenticatedAppFormFieldsRouteImport } from './routes/_authenticated/app/form-fields'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app/documents'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppAuditsRouteImport } from './routes/_authenticated/app/audits'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app/assets'
import { Route as AuthenticatedAppTrainingIndexRouteImport } from './routes/_authenticated/app/training.index'
import { Route as AuthenticatedAppPpeIndexRouteImport } from './routes/_authenticated/app/ppe.index'
import { Route as AuthenticatedAppInductionsIndexRouteImport } from './routes/_authenticated/app/inductions.index'
import { Route as AuthenticatedAppIncidentsIndexRouteImport } from './routes/_authenticated/app/incidents.index'
import { Route as AuthenticatedAppAuditsIndexRouteImport } from './routes/_authenticated/app/audits.index'
import { Route as AuthenticatedAppTrainingIdRouteImport } from './routes/_authenticated/app/training.$id'
import { Route as AuthenticatedAppPpeIdRouteImport } from './routes/_authenticated/app/ppe.$id'
import { Route as AuthenticatedAppInductionsIdRouteImport } from './routes/_authenticated/app/inductions.$id'
import { Route as AuthenticatedAppIncidentsCreateRouteImport } from './routes/_authenticated/app/incidents.create'
import { Route as AuthenticatedAppIncidentsIdRouteImport } from './routes/_authenticated/app/incidents.$id'
import { Route as AuthenticatedAppAuditsCreateRouteImport } from './routes/_authenticated/app/audits.create'
import { Route as AuthenticatedAppAuditsIdRouteImport } from './routes/_authenticated/app/audits.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppWasteRoute = AuthenticatedAppWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrainingRoute =
  AuthenticatedAppTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSitesRoute = AuthenticatedAppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPpeRoute = AuthenticatedAppPpeRouteImport.update({
  id: '/ppe',
  path: '/ppe',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInductionsRoute =
  AuthenticatedAppInductionsRouteImport.update({
    id: '/inductions',
    path: '/inductions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIncidentsRoute =
  AuthenticatedAppIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFormFieldsRoute =
  AuthenticatedAppFormFieldsRouteImport.update({
    id: '/form-fields',
    path: '/form-fields',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditsRoute = AuthenticatedAppAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrainingIndexRoute =
  AuthenticatedAppTrainingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTrainingRoute,
  } as any)
const AuthenticatedAppPpeIndexRoute =
  AuthenticatedAppPpeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPpeRoute,
  } as any)
const AuthenticatedAppInductionsIndexRoute =
  AuthenticatedAppInductionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInductionsRoute,
  } as any)
const AuthenticatedAppIncidentsIndexRoute =
  AuthenticatedAppIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppIncidentsRoute,
  } as any)
const AuthenticatedAppAuditsIndexRoute =
  AuthenticatedAppAuditsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAuditsRoute,
  } as any)
const AuthenticatedAppTrainingIdRoute =
  AuthenticatedAppTrainingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppTrainingRoute,
  } as any)
const AuthenticatedAppPpeIdRoute = AuthenticatedAppPpeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppPpeRoute,
} as any)
const AuthenticatedAppInductionsIdRoute =
  AuthenticatedAppInductionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppInductionsRoute,
  } as any)
const AuthenticatedAppIncidentsCreateRoute =
  AuthenticatedAppIncidentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAppIncidentsRoute,
  } as any)
const AuthenticatedAppIncidentsIdRoute =
  AuthenticatedAppIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppIncidentsRoute,
  } as any)
const AuthenticatedAppAuditsCreateRoute =
  AuthenticatedAppAuditsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAppAuditsRoute,
  } as any)
const AuthenticatedAppAuditsIdRoute =
  AuthenticatedAppAuditsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/audits': typeof AuthenticatedAppAuditsRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/form-fields': typeof AuthenticatedAppFormFieldsRoute
  '/app/incidents': typeof AuthenticatedAppIncidentsRouteWithChildren
  '/app/inductions': typeof AuthenticatedAppInductionsRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/ppe': typeof AuthenticatedAppPpeRouteWithChildren
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sites': typeof AuthenticatedAppSitesRoute
  '/app/training': typeof AuthenticatedAppTrainingRouteWithChildren
  '/app/waste': typeof AuthenticatedAppWasteRoute
  '/app/audits/$id': typeof AuthenticatedAppAuditsIdRoute
  '/app/audits/create': typeof AuthenticatedAppAuditsCreateRoute
  '/app/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/app/incidents/create': typeof AuthenticatedAppIncidentsCreateRoute
  '/app/inductions/$id': typeof AuthenticatedAppInductionsIdRoute
  '/app/ppe/$id': typeof AuthenticatedAppPpeIdRoute
  '/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/app/audits/': typeof AuthenticatedAppAuditsIndexRoute
  '/app/incidents/': typeof AuthenticatedAppIncidentsIndexRoute
  '/app/inductions/': typeof AuthenticatedAppInductionsIndexRoute
  '/app/ppe/': typeof AuthenticatedAppPpeIndexRoute
  '/app/training/': typeof AuthenticatedAppTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/form-fields': typeof AuthenticatedAppFormFieldsRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/sites': typeof AuthenticatedAppSitesRoute
  '/app/waste': typeof AuthenticatedAppWasteRoute
  '/app/audits/$id': typeof AuthenticatedAppAuditsIdRoute
  '/app/audits/create': typeof AuthenticatedAppAuditsCreateRoute
  '/app/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/app/incidents/create': typeof AuthenticatedAppIncidentsCreateRoute
  '/app/inductions/$id': typeof AuthenticatedAppInductionsIdRoute
  '/app/ppe/$id': typeof AuthenticatedAppPpeIdRoute
  '/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/app/audits': typeof AuthenticatedAppAuditsIndexRoute
  '/app/incidents': typeof AuthenticatedAppIncidentsIndexRoute
  '/app/inductions': typeof AuthenticatedAppInductionsIndexRoute
  '/app/ppe': typeof AuthenticatedAppPpeIndexRoute
  '/app/training': typeof AuthenticatedAppTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/app/audits': typeof AuthenticatedAppAuditsRouteWithChildren
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/form-fields': typeof AuthenticatedAppFormFieldsRoute
  '/_authenticated/app/incidents': typeof AuthenticatedAppIncidentsRouteWithChildren
  '/_authenticated/app/inductions': typeof AuthenticatedAppInductionsRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/ppe': typeof AuthenticatedAppPpeRouteWithChildren
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/sites': typeof AuthenticatedAppSitesRoute
  '/_authenticated/app/training': typeof AuthenticatedAppTrainingRouteWithChildren
  '/_authenticated/app/waste': typeof AuthenticatedAppWasteRoute
  '/_authenticated/app/audits/$id': typeof AuthenticatedAppAuditsIdRoute
  '/_authenticated/app/audits/create': typeof AuthenticatedAppAuditsCreateRoute
  '/_authenticated/app/incidents/$id': typeof AuthenticatedAppIncidentsIdRoute
  '/_authenticated/app/incidents/create': typeof AuthenticatedAppIncidentsCreateRoute
  '/_authenticated/app/inductions/$id': typeof AuthenticatedAppInductionsIdRoute
  '/_authenticated/app/ppe/$id': typeof AuthenticatedAppPpeIdRoute
  '/_authenticated/app/training/$id': typeof AuthenticatedAppTrainingIdRoute
  '/_authenticated/app/audits/': typeof AuthenticatedAppAuditsIndexRoute
  '/_authenticated/app/incidents/': typeof AuthenticatedAppIncidentsIndexRoute
  '/_authenticated/app/inductions/': typeof AuthenticatedAppInductionsIndexRoute
  '/_authenticated/app/ppe/': typeof AuthenticatedAppPpeIndexRoute
  '/_authenticated/app/training/': typeof AuthenticatedAppTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app'
    | '/app/assets'
    | '/app/audits'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/form-fields'
    | '/app/incidents'
    | '/app/inductions'
    | '/app/notifications'
    | '/app/ppe'
    | '/app/reports'
    | '/app/sites'
    | '/app/training'
    | '/app/waste'
    | '/app/audits/$id'
    | '/app/audits/create'
    | '/app/incidents/$id'
    | '/app/incidents/create'
    | '/app/inductions/$id'
    | '/app/ppe/$id'
    | '/app/training/$id'
    | '/app/audits/'
    | '/app/incidents/'
    | '/app/inductions/'
    | '/app/ppe/'
    | '/app/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app'
    | '/app/assets'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/form-fields'
    | '/app/notifications'
    | '/app/reports'
    | '/app/sites'
    | '/app/waste'
    | '/app/audits/$id'
    | '/app/audits/create'
    | '/app/incidents/$id'
    | '/app/incidents/create'
    | '/app/inductions/$id'
    | '/app/ppe/$id'
    | '/app/training/$id'
    | '/app/audits'
    | '/app/incidents'
    | '/app/inductions'
    | '/app/ppe'
    | '/app/training'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/audits'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/form-fields'
    | '/_authenticated/app/incidents'
    | '/_authenticated/app/inductions'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/ppe'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/sites'
    | '/_authenticated/app/training'
    | '/_authenticated/app/waste'
    | '/_authenticated/app/audits/$id'
    | '/_authenticated/app/audits/create'
    | '/_authenticated/app/incidents/$id'
    | '/_authenticated/app/incidents/create'
    | '/_authenticated/app/inductions/$id'
    | '/_authenticated/app/ppe/$id'
    | '/_authenticated/app/training/$id'
    | '/_authenticated/app/audits/'
    | '/_authenticated/app/incidents/'
    | '/_authenticated/app/inductions/'
    | '/_authenticated/app/ppe/'
    | '/_authenticated/app/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/waste': {
      id: '/_authenticated/app/waste'
      path: '/waste'
      fullPath: '/app/waste'
      preLoaderRoute: typeof AuthenticatedAppWasteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/training': {
      id: '/_authenticated/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AuthenticatedAppTrainingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sites': {
      id: '/_authenticated/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AuthenticatedAppSitesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ppe': {
      id: '/_authenticated/app/ppe'
      path: '/ppe'
      fullPath: '/app/ppe'
      preLoaderRoute: typeof AuthenticatedAppPpeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inductions': {
      id: '/_authenticated/app/inductions'
      path: '/inductions'
      fullPath: '/app/inductions'
      preLoaderRoute: typeof AuthenticatedAppInductionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/incidents': {
      id: '/_authenticated/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AuthenticatedAppIncidentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/form-fields': {
      id: '/_authenticated/app/form-fields'
      path: '/form-fields'
      fullPath: '/app/form-fields'
      preLoaderRoute: typeof AuthenticatedAppFormFieldsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audits': {
      id: '/_authenticated/app/audits'
      path: '/audits'
      fullPath: '/app/audits'
      preLoaderRoute: typeof AuthenticatedAppAuditsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/training/': {
      id: '/_authenticated/app/training/'
      path: '/'
      fullPath: '/app/training/'
      preLoaderRoute: typeof AuthenticatedAppTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedAppTrainingRoute
    }
    '/_authenticated/app/ppe/': {
      id: '/_authenticated/app/ppe/'
      path: '/'
      fullPath: '/app/ppe/'
      preLoaderRoute: typeof AuthenticatedAppPpeIndexRouteImport
      parentRoute: typeof AuthenticatedAppPpeRoute
    }
    '/_authenticated/app/inductions/': {
      id: '/_authenticated/app/inductions/'
      path: '/'
      fullPath: '/app/inductions/'
      preLoaderRoute: typeof AuthenticatedAppInductionsIndexRouteImport
      parentRoute: typeof AuthenticatedAppInductionsRoute
    }
    '/_authenticated/app/incidents/': {
      id: '/_authenticated/app/incidents/'
      path: '/'
      fullPath: '/app/incidents/'
      preLoaderRoute: typeof AuthenticatedAppIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppIncidentsRoute
    }
    '/_authenticated/app/audits/': {
      id: '/_authenticated/app/audits/'
      path: '/'
      fullPath: '/app/audits/'
      preLoaderRoute: typeof AuthenticatedAppAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedAppAuditsRoute
    }
    '/_authenticated/app/training/$id': {
      id: '/_authenticated/app/training/$id'
      path: '/$id'
      fullPath: '/app/training/$id'
      preLoaderRoute: typeof AuthenticatedAppTrainingIdRouteImport
      parentRoute: typeof AuthenticatedAppTrainingRoute
    }
    '/_authenticated/app/ppe/$id': {
      id: '/_authenticated/app/ppe/$id'
      path: '/$id'
      fullPath: '/app/ppe/$id'
      preLoaderRoute: typeof AuthenticatedAppPpeIdRouteImport
      parentRoute: typeof AuthenticatedAppPpeRoute
    }
    '/_authenticated/app/inductions/$id': {
      id: '/_authenticated/app/inductions/$id'
      path: '/$id'
      fullPath: '/app/inductions/$id'
      preLoaderRoute: typeof AuthenticatedAppInductionsIdRouteImport
      parentRoute: typeof AuthenticatedAppInductionsRoute
    }
    '/_authenticated/app/incidents/create': {
      id: '/_authenticated/app/incidents/create'
      path: '/create'
      fullPath: '/app/incidents/create'
      preLoaderRoute: typeof AuthenticatedAppIncidentsCreateRouteImport
      parentRoute: typeof AuthenticatedAppIncidentsRoute
    }
    '/_authenticated/app/incidents/$id': {
      id: '/_authenticated/app/incidents/$id'
      path: '/$id'
      fullPath: '/app/incidents/$id'
      preLoaderRoute: typeof AuthenticatedAppIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedAppIncidentsRoute
    }
    '/_authenticated/app/audits/create': {
      id: '/_authenticated/app/audits/create'
      path: '/create'
      fullPath: '/app/audits/create'
      preLoaderRoute: typeof AuthenticatedAppAuditsCreateRouteImport
      parentRoute: typeof AuthenticatedAppAuditsRoute
    }
    '/_authenticated/app/audits/$id': {
      id: '/_authenticated/app/audits/$id'
      path: '/$id'
      fullPath: '/app/audits/$id'
      preLoaderRoute: typeof AuthenticatedAppAuditsIdRouteImport
      parentRoute: typeof AuthenticatedAppAuditsRoute
    }
  }
}

interface AuthenticatedAppAuditsRouteChildren {
  AuthenticatedAppAuditsIdRoute: typeof AuthenticatedAppAuditsIdRoute
  AuthenticatedAppAuditsCreateRoute: typeof AuthenticatedAppAuditsCreateRoute
  AuthenticatedAppAuditsIndexRoute: typeof AuthenticatedAppAuditsIndexRoute
}

const AuthenticatedAppAuditsRouteChildren: AuthenticatedAppAuditsRouteChildren =
  {
    AuthenticatedAppAuditsIdRoute: AuthenticatedAppAuditsIdRoute,
    AuthenticatedAppAuditsCreateRoute: AuthenticatedAppAuditsCreateRoute,
    AuthenticatedAppAuditsIndexRoute: AuthenticatedAppAuditsIndexRoute,
  }

const AuthenticatedAppAuditsRouteWithChildren =
  AuthenticatedAppAuditsRoute._addFileChildren(
    AuthenticatedAppAuditsRouteChildren,
  )

interface AuthenticatedAppIncidentsRouteChildren {
  AuthenticatedAppIncidentsIdRoute: typeof AuthenticatedAppIncidentsIdRoute
  AuthenticatedAppIncidentsCreateRoute: typeof AuthenticatedAppIncidentsCreateRoute
  AuthenticatedAppIncidentsIndexRoute: typeof AuthenticatedAppIncidentsIndexRoute
}

const AuthenticatedAppIncidentsRouteChildren: AuthenticatedAppIncidentsRouteChildren =
  {
    AuthenticatedAppIncidentsIdRoute: AuthenticatedAppIncidentsIdRoute,
    AuthenticatedAppIncidentsCreateRoute: AuthenticatedAppIncidentsCreateRoute,
    AuthenticatedAppIncidentsIndexRoute: AuthenticatedAppIncidentsIndexRoute,
  }

const AuthenticatedAppIncidentsRouteWithChildren =
  AuthenticatedAppIncidentsRoute._addFileChildren(
    AuthenticatedAppIncidentsRouteChildren,
  )

interface AuthenticatedAppInductionsRouteChildren {
  AuthenticatedAppInductionsIdRoute: typeof AuthenticatedAppInductionsIdRoute
  AuthenticatedAppInductionsIndexRoute: typeof AuthenticatedAppInductionsIndexRoute
}

const AuthenticatedAppInductionsRouteChildren: AuthenticatedAppInductionsRouteChildren =
  {
    AuthenticatedAppInductionsIdRoute: AuthenticatedAppInductionsIdRoute,
    AuthenticatedAppInductionsIndexRoute: AuthenticatedAppInductionsIndexRoute,
  }

const AuthenticatedAppInductionsRouteWithChildren =
  AuthenticatedAppInductionsRoute._addFileChildren(
    AuthenticatedAppInductionsRouteChildren,
  )

interface AuthenticatedAppPpeRouteChildren {
  AuthenticatedAppPpeIdRoute: typeof AuthenticatedAppPpeIdRoute
  AuthenticatedAppPpeIndexRoute: typeof AuthenticatedAppPpeIndexRoute
}

const AuthenticatedAppPpeRouteChildren: AuthenticatedAppPpeRouteChildren = {
  AuthenticatedAppPpeIdRoute: AuthenticatedAppPpeIdRoute,
  AuthenticatedAppPpeIndexRoute: AuthenticatedAppPpeIndexRoute,
}

const AuthenticatedAppPpeRouteWithChildren =
  AuthenticatedAppPpeRoute._addFileChildren(AuthenticatedAppPpeRouteChildren)

interface AuthenticatedAppTrainingRouteChildren {
  AuthenticatedAppTrainingIdRoute: typeof AuthenticatedAppTrainingIdRoute
  AuthenticatedAppTrainingIndexRoute: typeof AuthenticatedAppTrainingIndexRoute
}

const AuthenticatedAppTrainingRouteChildren: AuthenticatedAppTrainingRouteChildren =
  {
    AuthenticatedAppTrainingIdRoute: AuthenticatedAppTrainingIdRoute,
    AuthenticatedAppTrainingIndexRoute: AuthenticatedAppTrainingIndexRoute,
  }

const AuthenticatedAppTrainingRouteWithChildren =
  AuthenticatedAppTrainingRoute._addFileChildren(
    AuthenticatedAppTrainingRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppAuditsRoute: typeof AuthenticatedAppAuditsRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppFormFieldsRoute: typeof AuthenticatedAppFormFieldsRoute
  AuthenticatedAppIncidentsRoute: typeof AuthenticatedAppIncidentsRouteWithChildren
  AuthenticatedAppInductionsRoute: typeof AuthenticatedAppInductionsRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppPpeRoute: typeof AuthenticatedAppPpeRouteWithChildren
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSitesRoute: typeof AuthenticatedAppSitesRoute
  AuthenticatedAppTrainingRoute: typeof AuthenticatedAppTrainingRouteWithChildren
  AuthenticatedAppWasteRoute: typeof AuthenticatedAppWasteRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppAuditsRoute: AuthenticatedAppAuditsRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppFormFieldsRoute: AuthenticatedAppFormFieldsRoute,
  AuthenticatedAppIncidentsRoute: AuthenticatedAppIncidentsRouteWithChildren,
  AuthenticatedAppInductionsRoute: AuthenticatedAppInductionsRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppPpeRoute: AuthenticatedAppPpeRouteWithChildren,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSitesRoute: AuthenticatedAppSitesRoute,
  AuthenticatedAppTrainingRoute: AuthenticatedAppTrainingRouteWithChildren,
  AuthenticatedAppWasteRoute: AuthenticatedAppWasteRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
