/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated.incidents'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated.facilities'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated.audits'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedIncidentsCreateRouteImport } from './routes/_authenticated.incidents.create'
import { Route as AuthenticatedIncidentsIdRouteImport } from './routes/_authenticated.incidents.$id'
import { Route as AuthenticatedFacilitiesCreateRouteImport } from './routes/_authenticated.facilities.create'
import { Route as AuthenticatedFacilitiesIdRouteImport } from './routes/_authenticated.facilities.$id'
import { Route as AuthenticatedCompaniesCreateRouteImport } from './routes/_authenticated.companies.create'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated.companies.$id'
import { Route as AuthenticatedAuditsCreateRouteImport } from './routes/_authenticated.audits.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsCreateRoute =
  AuthenticatedIncidentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsIdRoute =
  AuthenticatedIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedFacilitiesCreateRoute =
  AuthenticatedFacilitiesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedFacilitiesRoute,
  } as any)
const AuthenticatedFacilitiesIdRoute =
  AuthenticatedFacilitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFacilitiesRoute,
  } as any)
const AuthenticatedCompaniesCreateRoute =
  AuthenticatedCompaniesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedAuditsCreateRoute =
  AuthenticatedAuditsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/_authenticated/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/_authenticated/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/_authenticated/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/_authenticated/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/audits'
    | '/companies'
    | '/dashboard'
    | '/facilities'
    | '/incidents'
    | '/settings'
    | '/audits/create'
    | '/companies/$id'
    | '/companies/create'
    | '/facilities/$id'
    | '/facilities/create'
    | '/incidents/$id'
    | '/incidents/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/audits'
    | '/companies'
    | '/dashboard'
    | '/facilities'
    | '/incidents'
    | '/settings'
    | '/audits/create'
    | '/companies/$id'
    | '/companies/create'
    | '/facilities/$id'
    | '/facilities/create'
    | '/incidents/$id'
    | '/incidents/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity'
    | '/_authenticated/audits'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/facilities'
    | '/_authenticated/incidents'
    | '/_authenticated/settings'
    | '/_authenticated/audits/create'
    | '/_authenticated/companies/$id'
    | '/_authenticated/companies/create'
    | '/_authenticated/facilities/$id'
    | '/_authenticated/facilities/create'
    | '/_authenticated/incidents/$id'
    | '/_authenticated/incidents/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents/create': {
      id: '/_authenticated/incidents/create'
      path: '/create'
      fullPath: '/incidents/create'
      preLoaderRoute: typeof AuthenticatedIncidentsCreateRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/$id': {
      id: '/_authenticated/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/facilities/create': {
      id: '/_authenticated/facilities/create'
      path: '/create'
      fullPath: '/facilities/create'
      preLoaderRoute: typeof AuthenticatedFacilitiesCreateRouteImport
      parentRoute: typeof AuthenticatedFacilitiesRoute
    }
    '/_authenticated/facilities/$id': {
      id: '/_authenticated/facilities/$id'
      path: '/$id'
      fullPath: '/facilities/$id'
      preLoaderRoute: typeof AuthenticatedFacilitiesIdRouteImport
      parentRoute: typeof AuthenticatedFacilitiesRoute
    }
    '/_authenticated/companies/create': {
      id: '/_authenticated/companies/create'
      path: '/create'
      fullPath: '/companies/create'
      preLoaderRoute: typeof AuthenticatedCompaniesCreateRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/audits/create': {
      id: '/_authenticated/audits/create'
      path: '/create'
      fullPath: '/audits/create'
      preLoaderRoute: typeof AuthenticatedAuditsCreateRouteImport
      parentRoute: typeof AuthenticatedAuditsRoute
    }
  }
}

interface AuthenticatedAuditsRouteChildren {
  AuthenticatedAuditsCreateRoute: typeof AuthenticatedAuditsCreateRoute
}

const AuthenticatedAuditsRouteChildren: AuthenticatedAuditsRouteChildren = {
  AuthenticatedAuditsCreateRoute: AuthenticatedAuditsCreateRoute,
}

const AuthenticatedAuditsRouteWithChildren =
  AuthenticatedAuditsRoute._addFileChildren(AuthenticatedAuditsRouteChildren)

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedCompaniesCreateRoute: typeof AuthenticatedCompaniesCreateRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
    AuthenticatedCompaniesCreateRoute: AuthenticatedCompaniesCreateRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedFacilitiesRouteChildren {
  AuthenticatedFacilitiesIdRoute: typeof AuthenticatedFacilitiesIdRoute
  AuthenticatedFacilitiesCreateRoute: typeof AuthenticatedFacilitiesCreateRoute
}

const AuthenticatedFacilitiesRouteChildren: AuthenticatedFacilitiesRouteChildren =
  {
    AuthenticatedFacilitiesIdRoute: AuthenticatedFacilitiesIdRoute,
    AuthenticatedFacilitiesCreateRoute: AuthenticatedFacilitiesCreateRoute,
  }

const AuthenticatedFacilitiesRouteWithChildren =
  AuthenticatedFacilitiesRoute._addFileChildren(
    AuthenticatedFacilitiesRouteChildren,
  )

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIdRoute: typeof AuthenticatedIncidentsIdRoute
  AuthenticatedIncidentsCreateRoute: typeof AuthenticatedIncidentsCreateRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIdRoute: AuthenticatedIncidentsIdRoute,
    AuthenticatedIncidentsCreateRoute: AuthenticatedIncidentsCreateRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRouteWithChildren
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRouteWithChildren
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAuditsRoute: AuthenticatedAuditsRouteWithChildren,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRouteWithChildren,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
