/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated.webhooks'
import { Route as AuthenticatedWasteRouteImport } from './routes/_authenticated.waste'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated.training'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated.roles'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPpeRouteImport } from './routes/_authenticated.ppe'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedInductionsRouteImport } from './routes/_authenticated.inductions'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated.incidents'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated.facilities'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated.audits'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated.assets'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as AuthenticatedIncidentsCreateRouteImport } from './routes/_authenticated.incidents.create'
import { Route as AuthenticatedIncidentsIdRouteImport } from './routes/_authenticated.incidents.$id'
import { Route as AuthenticatedFacilitiesCreateRouteImport } from './routes/_authenticated.facilities.create'
import { Route as AuthenticatedFacilitiesIdRouteImport } from './routes/_authenticated.facilities.$id'
import { Route as AuthenticatedCompaniesCreateRouteImport } from './routes/_authenticated.companies.create'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated.companies.$id'
import { Route as AuthenticatedAuditsCreateRouteImport } from './routes/_authenticated.audits.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWasteRoute = AuthenticatedWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPpeRoute = AuthenticatedPpeRouteImport.update({
  id: '/ppe',
  path: '/ppe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInductionsRoute = AuthenticatedInductionsRouteImport.update({
  id: '/inductions',
  path: '/inductions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsCreateRoute =
  AuthenticatedIncidentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsIdRoute =
  AuthenticatedIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedFacilitiesCreateRoute =
  AuthenticatedFacilitiesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedFacilitiesRoute,
  } as any)
const AuthenticatedFacilitiesIdRoute =
  AuthenticatedFacilitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFacilitiesRoute,
  } as any)
const AuthenticatedCompaniesCreateRoute =
  AuthenticatedCompaniesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedAuditsCreateRoute =
  AuthenticatedAuditsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/inductions': typeof AuthenticatedInductionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ppe': typeof AuthenticatedPpeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/waste': typeof AuthenticatedWasteRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/inductions': typeof AuthenticatedInductionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/ppe': typeof AuthenticatedPpeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/waste': typeof AuthenticatedWasteRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRouteWithChildren
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/inductions': typeof AuthenticatedInductionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/ppe': typeof AuthenticatedPpeRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/waste': typeof AuthenticatedWasteRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/audits/create': typeof AuthenticatedAuditsCreateRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/companies/create': typeof AuthenticatedCompaniesCreateRoute
  '/_authenticated/facilities/$id': typeof AuthenticatedFacilitiesIdRoute
  '/_authenticated/facilities/create': typeof AuthenticatedFacilitiesCreateRoute
  '/_authenticated/incidents/$id': typeof AuthenticatedIncidentsIdRoute
  '/_authenticated/incidents/create': typeof AuthenticatedIncidentsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/assets'
    | '/audits'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/facilities'
    | '/incidents'
    | '/inductions'
    | '/notifications'
    | '/ppe'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/training'
    | '/users'
    | '/waste'
    | '/webhooks'
    | '/audits/create'
    | '/companies/$id'
    | '/companies/create'
    | '/facilities/$id'
    | '/facilities/create'
    | '/incidents/$id'
    | '/incidents/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/assets'
    | '/audits'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/facilities'
    | '/incidents'
    | '/inductions'
    | '/notifications'
    | '/ppe'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/training'
    | '/users'
    | '/waste'
    | '/webhooks'
    | '/audits/create'
    | '/companies/$id'
    | '/companies/create'
    | '/facilities/$id'
    | '/facilities/create'
    | '/incidents/$id'
    | '/incidents/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity'
    | '/_authenticated/assets'
    | '/_authenticated/audits'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/facilities'
    | '/_authenticated/incidents'
    | '/_authenticated/inductions'
    | '/_authenticated/notifications'
    | '/_authenticated/ppe'
    | '/_authenticated/reports'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/training'
    | '/_authenticated/users'
    | '/_authenticated/waste'
    | '/_authenticated/webhooks'
    | '/_authenticated/audits/create'
    | '/_authenticated/companies/$id'
    | '/_authenticated/companies/create'
    | '/_authenticated/facilities/$id'
    | '/_authenticated/facilities/create'
    | '/_authenticated/incidents/$id'
    | '/_authenticated/incidents/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/waste': {
      id: '/_authenticated/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof AuthenticatedWasteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ppe': {
      id: '/_authenticated/ppe'
      path: '/ppe'
      fullPath: '/ppe'
      preLoaderRoute: typeof AuthenticatedPpeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inductions': {
      id: '/_authenticated/inductions'
      path: '/inductions'
      fullPath: '/inductions'
      preLoaderRoute: typeof AuthenticatedInductionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents/create': {
      id: '/_authenticated/incidents/create'
      path: '/create'
      fullPath: '/incidents/create'
      preLoaderRoute: typeof AuthenticatedIncidentsCreateRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/$id': {
      id: '/_authenticated/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AuthenticatedIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/facilities/create': {
      id: '/_authenticated/facilities/create'
      path: '/create'
      fullPath: '/facilities/create'
      preLoaderRoute: typeof AuthenticatedFacilitiesCreateRouteImport
      parentRoute: typeof AuthenticatedFacilitiesRoute
    }
    '/_authenticated/facilities/$id': {
      id: '/_authenticated/facilities/$id'
      path: '/$id'
      fullPath: '/facilities/$id'
      preLoaderRoute: typeof AuthenticatedFacilitiesIdRouteImport
      parentRoute: typeof AuthenticatedFacilitiesRoute
    }
    '/_authenticated/companies/create': {
      id: '/_authenticated/companies/create'
      path: '/create'
      fullPath: '/companies/create'
      preLoaderRoute: typeof AuthenticatedCompaniesCreateRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/audits/create': {
      id: '/_authenticated/audits/create'
      path: '/create'
      fullPath: '/audits/create'
      preLoaderRoute: typeof AuthenticatedAuditsCreateRouteImport
      parentRoute: typeof AuthenticatedAuditsRoute
    }
  }
}

interface AuthenticatedAuditsRouteChildren {
  AuthenticatedAuditsCreateRoute: typeof AuthenticatedAuditsCreateRoute
}

const AuthenticatedAuditsRouteChildren: AuthenticatedAuditsRouteChildren = {
  AuthenticatedAuditsCreateRoute: AuthenticatedAuditsCreateRoute,
}

const AuthenticatedAuditsRouteWithChildren =
  AuthenticatedAuditsRoute._addFileChildren(AuthenticatedAuditsRouteChildren)

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedCompaniesCreateRoute: typeof AuthenticatedCompaniesCreateRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
    AuthenticatedCompaniesCreateRoute: AuthenticatedCompaniesCreateRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedFacilitiesRouteChildren {
  AuthenticatedFacilitiesIdRoute: typeof AuthenticatedFacilitiesIdRoute
  AuthenticatedFacilitiesCreateRoute: typeof AuthenticatedFacilitiesCreateRoute
}

const AuthenticatedFacilitiesRouteChildren: AuthenticatedFacilitiesRouteChildren =
  {
    AuthenticatedFacilitiesIdRoute: AuthenticatedFacilitiesIdRoute,
    AuthenticatedFacilitiesCreateRoute: AuthenticatedFacilitiesCreateRoute,
  }

const AuthenticatedFacilitiesRouteWithChildren =
  AuthenticatedFacilitiesRoute._addFileChildren(
    AuthenticatedFacilitiesRouteChildren,
  )

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIdRoute: typeof AuthenticatedIncidentsIdRoute
  AuthenticatedIncidentsCreateRoute: typeof AuthenticatedIncidentsCreateRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIdRoute: AuthenticatedIncidentsIdRoute,
    AuthenticatedIncidentsCreateRoute: AuthenticatedIncidentsCreateRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRouteWithChildren
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRouteWithChildren
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedInductionsRoute: typeof AuthenticatedInductionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPpeRoute: typeof AuthenticatedPpeRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWasteRoute: typeof AuthenticatedWasteRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditsRoute: AuthenticatedAuditsRouteWithChildren,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRouteWithChildren,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedInductionsRoute: AuthenticatedInductionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPpeRoute: AuthenticatedPpeRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWasteRoute: AuthenticatedWasteRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
