/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalTrainingRouteImport } from './routes/_authenticated/portal/training'
import { Route as AuthenticatedPortalSitesRouteImport } from './routes/_authenticated/portal/sites'
import { Route as AuthenticatedPortalReportsRouteImport } from './routes/_authenticated/portal/reports'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal/notifications'
import { Route as AuthenticatedPortalInductionsRouteImport } from './routes/_authenticated/portal/inductions'
import { Route as AuthenticatedPortalIncidentsRouteImport } from './routes/_authenticated/portal/incidents'
import { Route as AuthenticatedPortalFeedbackRouteImport } from './routes/_authenticated/portal/feedback'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalDashboardRouteImport } from './routes/_authenticated/portal/dashboard'
import { Route as AuthenticatedPortalAuditsRouteImport } from './routes/_authenticated/portal/audits'
import { Route as AuthenticatedPortalTrainingIndexRouteImport } from './routes/_authenticated/portal/training.index'
import { Route as AuthenticatedPortalInductionsIndexRouteImport } from './routes/_authenticated/portal/inductions.index'
import { Route as AuthenticatedPortalIncidentsIndexRouteImport } from './routes/_authenticated/portal/incidents.index'
import { Route as AuthenticatedPortalAuditsIndexRouteImport } from './routes/_authenticated/portal/audits.index'
import { Route as AuthenticatedPortalTrainingIdRouteImport } from './routes/_authenticated/portal/training.$id'
import { Route as AuthenticatedPortalInductionsIdRouteImport } from './routes/_authenticated/portal/inductions.$id'
import { Route as AuthenticatedPortalIncidentsIdRouteImport } from './routes/_authenticated/portal/incidents.$id'
import { Route as AuthenticatedPortalAuditsIdRouteImport } from './routes/_authenticated/portal/audits.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalTrainingRoute =
  AuthenticatedPortalTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSitesRoute =
  AuthenticatedPortalSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReportsRoute =
  AuthenticatedPortalReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInductionsRoute =
  AuthenticatedPortalInductionsRouteImport.update({
    id: '/inductions',
    path: '/inductions',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalIncidentsRoute =
  AuthenticatedPortalIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFeedbackRoute =
  AuthenticatedPortalFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDashboardRoute =
  AuthenticatedPortalDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAuditsRoute =
  AuthenticatedPortalAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalTrainingIndexRoute =
  AuthenticatedPortalTrainingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalTrainingRoute,
  } as any)
const AuthenticatedPortalInductionsIndexRoute =
  AuthenticatedPortalInductionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalInductionsRoute,
  } as any)
const AuthenticatedPortalIncidentsIndexRoute =
  AuthenticatedPortalIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalIncidentsRoute,
  } as any)
const AuthenticatedPortalAuditsIndexRoute =
  AuthenticatedPortalAuditsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalAuditsRoute,
  } as any)
const AuthenticatedPortalTrainingIdRoute =
  AuthenticatedPortalTrainingIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalTrainingRoute,
  } as any)
const AuthenticatedPortalInductionsIdRoute =
  AuthenticatedPortalInductionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalInductionsRoute,
  } as any)
const AuthenticatedPortalIncidentsIdRoute =
  AuthenticatedPortalIncidentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalIncidentsRoute,
  } as any)
const AuthenticatedPortalAuditsIdRoute =
  AuthenticatedPortalAuditsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalAuditsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/audits': typeof AuthenticatedPortalAuditsRouteWithChildren
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/portal/incidents': typeof AuthenticatedPortalIncidentsRouteWithChildren
  '/portal/inductions': typeof AuthenticatedPortalInductionsRouteWithChildren
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/sites': typeof AuthenticatedPortalSitesRoute
  '/portal/training': typeof AuthenticatedPortalTrainingRouteWithChildren
  '/portal/audits/$id': typeof AuthenticatedPortalAuditsIdRoute
  '/portal/incidents/$id': typeof AuthenticatedPortalIncidentsIdRoute
  '/portal/inductions/$id': typeof AuthenticatedPortalInductionsIdRoute
  '/portal/training/$id': typeof AuthenticatedPortalTrainingIdRoute
  '/portal/audits/': typeof AuthenticatedPortalAuditsIndexRoute
  '/portal/incidents/': typeof AuthenticatedPortalIncidentsIndexRoute
  '/portal/inductions/': typeof AuthenticatedPortalInductionsIndexRoute
  '/portal/training/': typeof AuthenticatedPortalTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/portal/sites': typeof AuthenticatedPortalSitesRoute
  '/portal/audits/$id': typeof AuthenticatedPortalAuditsIdRoute
  '/portal/incidents/$id': typeof AuthenticatedPortalIncidentsIdRoute
  '/portal/inductions/$id': typeof AuthenticatedPortalInductionsIdRoute
  '/portal/training/$id': typeof AuthenticatedPortalTrainingIdRoute
  '/portal/audits': typeof AuthenticatedPortalAuditsIndexRoute
  '/portal/incidents': typeof AuthenticatedPortalIncidentsIndexRoute
  '/portal/inductions': typeof AuthenticatedPortalInductionsIndexRoute
  '/portal/training': typeof AuthenticatedPortalTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/portal/audits': typeof AuthenticatedPortalAuditsRouteWithChildren
  '/_authenticated/portal/dashboard': typeof AuthenticatedPortalDashboardRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/feedback': typeof AuthenticatedPortalFeedbackRoute
  '/_authenticated/portal/incidents': typeof AuthenticatedPortalIncidentsRouteWithChildren
  '/_authenticated/portal/inductions': typeof AuthenticatedPortalInductionsRouteWithChildren
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/reports': typeof AuthenticatedPortalReportsRoute
  '/_authenticated/portal/sites': typeof AuthenticatedPortalSitesRoute
  '/_authenticated/portal/training': typeof AuthenticatedPortalTrainingRouteWithChildren
  '/_authenticated/portal/audits/$id': typeof AuthenticatedPortalAuditsIdRoute
  '/_authenticated/portal/incidents/$id': typeof AuthenticatedPortalIncidentsIdRoute
  '/_authenticated/portal/inductions/$id': typeof AuthenticatedPortalInductionsIdRoute
  '/_authenticated/portal/training/$id': typeof AuthenticatedPortalTrainingIdRoute
  '/_authenticated/portal/audits/': typeof AuthenticatedPortalAuditsIndexRoute
  '/_authenticated/portal/incidents/': typeof AuthenticatedPortalIncidentsIndexRoute
  '/_authenticated/portal/inductions/': typeof AuthenticatedPortalInductionsIndexRoute
  '/_authenticated/portal/training/': typeof AuthenticatedPortalTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal'
    | '/portal/audits'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/feedback'
    | '/portal/incidents'
    | '/portal/inductions'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/sites'
    | '/portal/training'
    | '/portal/audits/$id'
    | '/portal/incidents/$id'
    | '/portal/inductions/$id'
    | '/portal/training/$id'
    | '/portal/audits/'
    | '/portal/incidents/'
    | '/portal/inductions/'
    | '/portal/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/portal'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/feedback'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/sites'
    | '/portal/audits/$id'
    | '/portal/incidents/$id'
    | '/portal/inductions/$id'
    | '/portal/training/$id'
    | '/portal/audits'
    | '/portal/incidents'
    | '/portal/inductions'
    | '/portal/training'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/portal'
    | '/_authenticated/portal/audits'
    | '/_authenticated/portal/dashboard'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/feedback'
    | '/_authenticated/portal/incidents'
    | '/_authenticated/portal/inductions'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/reports'
    | '/_authenticated/portal/sites'
    | '/_authenticated/portal/training'
    | '/_authenticated/portal/audits/$id'
    | '/_authenticated/portal/incidents/$id'
    | '/_authenticated/portal/inductions/$id'
    | '/_authenticated/portal/training/$id'
    | '/_authenticated/portal/audits/'
    | '/_authenticated/portal/incidents/'
    | '/_authenticated/portal/inductions/'
    | '/_authenticated/portal/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/training': {
      id: '/_authenticated/portal/training'
      path: '/training'
      fullPath: '/portal/training'
      preLoaderRoute: typeof AuthenticatedPortalTrainingRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/sites': {
      id: '/_authenticated/portal/sites'
      path: '/sites'
      fullPath: '/portal/sites'
      preLoaderRoute: typeof AuthenticatedPortalSitesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/reports': {
      id: '/_authenticated/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof AuthenticatedPortalReportsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/inductions': {
      id: '/_authenticated/portal/inductions'
      path: '/inductions'
      fullPath: '/portal/inductions'
      preLoaderRoute: typeof AuthenticatedPortalInductionsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/incidents': {
      id: '/_authenticated/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof AuthenticatedPortalIncidentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/feedback': {
      id: '/_authenticated/portal/feedback'
      path: '/feedback'
      fullPath: '/portal/feedback'
      preLoaderRoute: typeof AuthenticatedPortalFeedbackRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/dashboard': {
      id: '/_authenticated/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof AuthenticatedPortalDashboardRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/audits': {
      id: '/_authenticated/portal/audits'
      path: '/audits'
      fullPath: '/portal/audits'
      preLoaderRoute: typeof AuthenticatedPortalAuditsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/training/': {
      id: '/_authenticated/portal/training/'
      path: '/'
      fullPath: '/portal/training/'
      preLoaderRoute: typeof AuthenticatedPortalTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedPortalTrainingRoute
    }
    '/_authenticated/portal/inductions/': {
      id: '/_authenticated/portal/inductions/'
      path: '/'
      fullPath: '/portal/inductions/'
      preLoaderRoute: typeof AuthenticatedPortalInductionsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalInductionsRoute
    }
    '/_authenticated/portal/incidents/': {
      id: '/_authenticated/portal/incidents/'
      path: '/'
      fullPath: '/portal/incidents/'
      preLoaderRoute: typeof AuthenticatedPortalIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalIncidentsRoute
    }
    '/_authenticated/portal/audits/': {
      id: '/_authenticated/portal/audits/'
      path: '/'
      fullPath: '/portal/audits/'
      preLoaderRoute: typeof AuthenticatedPortalAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalAuditsRoute
    }
    '/_authenticated/portal/training/$id': {
      id: '/_authenticated/portal/training/$id'
      path: '/$id'
      fullPath: '/portal/training/$id'
      preLoaderRoute: typeof AuthenticatedPortalTrainingIdRouteImport
      parentRoute: typeof AuthenticatedPortalTrainingRoute
    }
    '/_authenticated/portal/inductions/$id': {
      id: '/_authenticated/portal/inductions/$id'
      path: '/$id'
      fullPath: '/portal/inductions/$id'
      preLoaderRoute: typeof AuthenticatedPortalInductionsIdRouteImport
      parentRoute: typeof AuthenticatedPortalInductionsRoute
    }
    '/_authenticated/portal/incidents/$id': {
      id: '/_authenticated/portal/incidents/$id'
      path: '/$id'
      fullPath: '/portal/incidents/$id'
      preLoaderRoute: typeof AuthenticatedPortalIncidentsIdRouteImport
      parentRoute: typeof AuthenticatedPortalIncidentsRoute
    }
    '/_authenticated/portal/audits/$id': {
      id: '/_authenticated/portal/audits/$id'
      path: '/$id'
      fullPath: '/portal/audits/$id'
      preLoaderRoute: typeof AuthenticatedPortalAuditsIdRouteImport
      parentRoute: typeof AuthenticatedPortalAuditsRoute
    }
  }
}

interface AuthenticatedPortalAuditsRouteChildren {
  AuthenticatedPortalAuditsIdRoute: typeof AuthenticatedPortalAuditsIdRoute
  AuthenticatedPortalAuditsIndexRoute: typeof AuthenticatedPortalAuditsIndexRoute
}

const AuthenticatedPortalAuditsRouteChildren: AuthenticatedPortalAuditsRouteChildren =
  {
    AuthenticatedPortalAuditsIdRoute: AuthenticatedPortalAuditsIdRoute,
    AuthenticatedPortalAuditsIndexRoute: AuthenticatedPortalAuditsIndexRoute,
  }

const AuthenticatedPortalAuditsRouteWithChildren =
  AuthenticatedPortalAuditsRoute._addFileChildren(
    AuthenticatedPortalAuditsRouteChildren,
  )

interface AuthenticatedPortalIncidentsRouteChildren {
  AuthenticatedPortalIncidentsIdRoute: typeof AuthenticatedPortalIncidentsIdRoute
  AuthenticatedPortalIncidentsIndexRoute: typeof AuthenticatedPortalIncidentsIndexRoute
}

const AuthenticatedPortalIncidentsRouteChildren: AuthenticatedPortalIncidentsRouteChildren =
  {
    AuthenticatedPortalIncidentsIdRoute: AuthenticatedPortalIncidentsIdRoute,
    AuthenticatedPortalIncidentsIndexRoute:
      AuthenticatedPortalIncidentsIndexRoute,
  }

const AuthenticatedPortalIncidentsRouteWithChildren =
  AuthenticatedPortalIncidentsRoute._addFileChildren(
    AuthenticatedPortalIncidentsRouteChildren,
  )

interface AuthenticatedPortalInductionsRouteChildren {
  AuthenticatedPortalInductionsIdRoute: typeof AuthenticatedPortalInductionsIdRoute
  AuthenticatedPortalInductionsIndexRoute: typeof AuthenticatedPortalInductionsIndexRoute
}

const AuthenticatedPortalInductionsRouteChildren: AuthenticatedPortalInductionsRouteChildren =
  {
    AuthenticatedPortalInductionsIdRoute: AuthenticatedPortalInductionsIdRoute,
    AuthenticatedPortalInductionsIndexRoute:
      AuthenticatedPortalInductionsIndexRoute,
  }

const AuthenticatedPortalInductionsRouteWithChildren =
  AuthenticatedPortalInductionsRoute._addFileChildren(
    AuthenticatedPortalInductionsRouteChildren,
  )

interface AuthenticatedPortalTrainingRouteChildren {
  AuthenticatedPortalTrainingIdRoute: typeof AuthenticatedPortalTrainingIdRoute
  AuthenticatedPortalTrainingIndexRoute: typeof AuthenticatedPortalTrainingIndexRoute
}

const AuthenticatedPortalTrainingRouteChildren: AuthenticatedPortalTrainingRouteChildren =
  {
    AuthenticatedPortalTrainingIdRoute: AuthenticatedPortalTrainingIdRoute,
    AuthenticatedPortalTrainingIndexRoute:
      AuthenticatedPortalTrainingIndexRoute,
  }

const AuthenticatedPortalTrainingRouteWithChildren =
  AuthenticatedPortalTrainingRoute._addFileChildren(
    AuthenticatedPortalTrainingRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAuditsRoute: typeof AuthenticatedPortalAuditsRouteWithChildren
  AuthenticatedPortalDashboardRoute: typeof AuthenticatedPortalDashboardRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalFeedbackRoute: typeof AuthenticatedPortalFeedbackRoute
  AuthenticatedPortalIncidentsRoute: typeof AuthenticatedPortalIncidentsRouteWithChildren
  AuthenticatedPortalInductionsRoute: typeof AuthenticatedPortalInductionsRouteWithChildren
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalReportsRoute: typeof AuthenticatedPortalReportsRoute
  AuthenticatedPortalSitesRoute: typeof AuthenticatedPortalSitesRoute
  AuthenticatedPortalTrainingRoute: typeof AuthenticatedPortalTrainingRouteWithChildren
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAuditsRoute: AuthenticatedPortalAuditsRouteWithChildren,
  AuthenticatedPortalDashboardRoute: AuthenticatedPortalDashboardRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalFeedbackRoute: AuthenticatedPortalFeedbackRoute,
  AuthenticatedPortalIncidentsRoute:
    AuthenticatedPortalIncidentsRouteWithChildren,
  AuthenticatedPortalInductionsRoute:
    AuthenticatedPortalInductionsRouteWithChildren,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalReportsRoute: AuthenticatedPortalReportsRoute,
  AuthenticatedPortalSitesRoute: AuthenticatedPortalSitesRoute,
  AuthenticatedPortalTrainingRoute:
    AuthenticatedPortalTrainingRouteWithChildren,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
