/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminWasteRouteImport } from './routes/_authenticated/admin/waste'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTrainingRouteImport } from './routes/_authenticated/admin/training'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin/tenants'
import { Route as AuthenticatedAdminSitesRouteImport } from './routes/_authenticated/admin/sites'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPpeRouteImport } from './routes/_authenticated/admin/ppe'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminInductionsRouteImport } from './routes/_authenticated/admin/inductions'
import { Route as AuthenticatedAdminIncidentsRouteImport } from './routes/_authenticated/admin/incidents'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin/companies'
import { Route as AuthenticatedAdminAuditsRouteImport } from './routes/_authenticated/admin/audits'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin/assets'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users.$id'
import { Route as AuthenticatedAdminSitesIdRouteImport } from './routes/_authenticated/admin/sites.$id'
import { Route as AuthenticatedAdminRolesIdRouteImport } from './routes/_authenticated/admin/roles.$id'
import { Route as AuthenticatedAdminCompaniesIdRouteImport } from './routes/_authenticated/admin/companies.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWasteRoute = AuthenticatedAdminWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTrainingRoute =
  AuthenticatedAdminTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSitesRoute = AuthenticatedAdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPpeRoute = AuthenticatedAdminPpeRouteImport.update({
  id: '/ppe',
  path: '/ppe',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInductionsRoute =
  AuthenticatedAdminInductionsRouteImport.update({
    id: '/inductions',
    path: '/inductions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncidentsRoute =
  AuthenticatedAdminIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditsRoute =
  AuthenticatedAdminAuditsRouteImport.update({
    id: '/audits',
    path: '/audits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminSitesIdRoute =
  AuthenticatedAdminSitesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminSitesRoute,
  } as any)
const AuthenticatedAdminRolesIdRoute =
  AuthenticatedAdminRolesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRolesRoute,
  } as any)
const AuthenticatedAdminCompaniesIdRoute =
  AuthenticatedAdminCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/inductions': typeof AuthenticatedAdminInductionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/ppe': typeof AuthenticatedAdminPpeRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sites': typeof AuthenticatedAdminSitesRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/waste': typeof AuthenticatedAdminWasteRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/admin/sites/$id': typeof AuthenticatedAdminSitesIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/inductions': typeof AuthenticatedAdminInductionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/ppe': typeof AuthenticatedAdminPpeRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sites': typeof AuthenticatedAdminSitesRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/waste': typeof AuthenticatedAdminWasteRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/admin/sites/$id': typeof AuthenticatedAdminSitesIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin/audits': typeof AuthenticatedAdminAuditsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/_authenticated/admin/inductions': typeof AuthenticatedAdminInductionsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/ppe': typeof AuthenticatedAdminPpeRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sites': typeof AuthenticatedAdminSitesRouteWithChildren
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/training': typeof AuthenticatedAdminTrainingRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/admin/waste': typeof AuthenticatedAdminWasteRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/companies/$id': typeof AuthenticatedAdminCompaniesIdRoute
  '/_authenticated/admin/roles/$id': typeof AuthenticatedAdminRolesIdRoute
  '/_authenticated/admin/sites/$id': typeof AuthenticatedAdminSitesIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/admin/activity'
    | '/admin/assets'
    | '/admin/audits'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/feedback'
    | '/admin/incidents'
    | '/admin/inductions'
    | '/admin/notifications'
    | '/admin/ppe'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/admin/waste'
    | '/admin/webhooks'
    | '/admin/companies/$id'
    | '/admin/roles/$id'
    | '/admin/sites/$id'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/admin/activity'
    | '/admin/assets'
    | '/admin/audits'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/feedback'
    | '/admin/incidents'
    | '/admin/inductions'
    | '/admin/notifications'
    | '/admin/ppe'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/tenants'
    | '/admin/training'
    | '/admin/users'
    | '/admin/waste'
    | '/admin/webhooks'
    | '/admin/companies/$id'
    | '/admin/roles/$id'
    | '/admin/sites/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/assets'
    | '/_authenticated/admin/audits'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/incidents'
    | '/_authenticated/admin/inductions'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/ppe'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sites'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/training'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/waste'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/companies/$id'
    | '/_authenticated/admin/roles/$id'
    | '/_authenticated/admin/sites/$id'
    | '/_authenticated/admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/waste': {
      id: '/_authenticated/admin/waste'
      path: '/waste'
      fullPath: '/admin/waste'
      preLoaderRoute: typeof AuthenticatedAdminWasteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/training': {
      id: '/_authenticated/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AuthenticatedAdminTrainingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sites': {
      id: '/_authenticated/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AuthenticatedAdminSitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ppe': {
      id: '/_authenticated/admin/ppe'
      path: '/ppe'
      fullPath: '/admin/ppe'
      preLoaderRoute: typeof AuthenticatedAdminPpeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inductions': {
      id: '/_authenticated/admin/inductions'
      path: '/inductions'
      fullPath: '/admin/inductions'
      preLoaderRoute: typeof AuthenticatedAdminInductionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incidents': {
      id: '/_authenticated/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audits': {
      id: '/_authenticated/admin/audits'
      path: '/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AuthenticatedAdminAuditsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/assets': {
      id: '/_authenticated/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/sites/$id': {
      id: '/_authenticated/admin/sites/$id'
      path: '/$id'
      fullPath: '/admin/sites/$id'
      preLoaderRoute: typeof AuthenticatedAdminSitesIdRouteImport
      parentRoute: typeof AuthenticatedAdminSitesRoute
    }
    '/_authenticated/admin/roles/$id': {
      id: '/_authenticated/admin/roles/$id'
      path: '/$id'
      fullPath: '/admin/roles/$id'
      preLoaderRoute: typeof AuthenticatedAdminRolesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRolesRoute
    }
    '/_authenticated/admin/companies/$id': {
      id: '/_authenticated/admin/companies/$id'
      path: '/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCompaniesRoute
    }
  }
}

interface AuthenticatedAdminCompaniesRouteChildren {
  AuthenticatedAdminCompaniesIdRoute: typeof AuthenticatedAdminCompaniesIdRoute
}

const AuthenticatedAdminCompaniesRouteChildren: AuthenticatedAdminCompaniesRouteChildren =
  {
    AuthenticatedAdminCompaniesIdRoute: AuthenticatedAdminCompaniesIdRoute,
  }

const AuthenticatedAdminCompaniesRouteWithChildren =
  AuthenticatedAdminCompaniesRoute._addFileChildren(
    AuthenticatedAdminCompaniesRouteChildren,
  )

interface AuthenticatedAdminRolesRouteChildren {
  AuthenticatedAdminRolesIdRoute: typeof AuthenticatedAdminRolesIdRoute
}

const AuthenticatedAdminRolesRouteChildren: AuthenticatedAdminRolesRouteChildren =
  {
    AuthenticatedAdminRolesIdRoute: AuthenticatedAdminRolesIdRoute,
  }

const AuthenticatedAdminRolesRouteWithChildren =
  AuthenticatedAdminRolesRoute._addFileChildren(
    AuthenticatedAdminRolesRouteChildren,
  )

interface AuthenticatedAdminSitesRouteChildren {
  AuthenticatedAdminSitesIdRoute: typeof AuthenticatedAdminSitesIdRoute
}

const AuthenticatedAdminSitesRouteChildren: AuthenticatedAdminSitesRouteChildren =
  {
    AuthenticatedAdminSitesIdRoute: AuthenticatedAdminSitesIdRoute,
  }

const AuthenticatedAdminSitesRouteWithChildren =
  AuthenticatedAdminSitesRoute._addFileChildren(
    AuthenticatedAdminSitesRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminAuditsRoute: typeof AuthenticatedAdminAuditsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminIncidentsRoute: typeof AuthenticatedAdminIncidentsRoute
  AuthenticatedAdminInductionsRoute: typeof AuthenticatedAdminInductionsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPpeRoute: typeof AuthenticatedAdminPpeRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSitesRoute: typeof AuthenticatedAdminSitesRouteWithChildren
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminTrainingRoute: typeof AuthenticatedAdminTrainingRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminWasteRoute: typeof AuthenticatedAdminWasteRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
  AuthenticatedAdminAuditsRoute: AuthenticatedAdminAuditsRoute,
  AuthenticatedAdminCompaniesRoute:
    AuthenticatedAdminCompaniesRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminIncidentsRoute: AuthenticatedAdminIncidentsRoute,
  AuthenticatedAdminInductionsRoute: AuthenticatedAdminInductionsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPpeRoute: AuthenticatedAdminPpeRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSitesRoute: AuthenticatedAdminSitesRouteWithChildren,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminTrainingRoute: AuthenticatedAdminTrainingRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminWasteRoute: AuthenticatedAdminWasteRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
